# GHABI Malek — Projet Majordhom
# Fichier : docker-compose.yml
# Description :
#   Configuration Docker du projet.
#   Lance automatiquement Apache/PHP, MySQL et phpMyAdmin.
#
# Rôle :
#   - Permet de développer et tester le projet localement sans installation manuelle.
#   - Facilite la maintenance et la compatibilité entre environnements.
#
# Accès :
#   - Site web : http://localhost
#   - phpMyAdmin : http://localhost:8080
#
# Sécurité :
#   - L’utilisation de Docker évite la manipulation directe de la base locale.
services:
  db:
    image: mysql:8.4
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: verysecurepassword
      MYSQL_DATABASE: majordhom
      TZ: Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    # image multi-arch (pas besoin de platform:)
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M
    depends_on:
      - db
    ports:
      - "8080:80"

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db