# GHABI Malek — Projet Majordhom
# Fichier : docker-compose.yml
# Description :
#   Configuration Docker du projet.
#   Lance automatiquement Apache/PHP, MySQL et phpMyAdmin.
#
# Rôle :
#   - Permet de développer et tester le projet localement sans installation manuelle.
#   - Facilite la maintenance et la compatibilité entre environnements.
#
# Accès :
#   - Site web : http://localhost
#   - phpMyAdmin : http://localhost:8080
#
# Sécurité :
#   - L’utilisation de Docker évite la manipulation directe de la base locale.



version: '1'

services:
  # MYSQL
  db:
    image: mysql:8.4
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecurepassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db:db

  # APACHE
  apache:
    image: lavoweb/php-8.3
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db:database